# Generated by Django 2.1 on 2020-07-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200730_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Code',
            new_name='code',
        ),
    ]
